<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="Indu" failures="0" tests="1" name="Default test" time="10.672" errors="0" timestamp="2023-11-10T13:31:20 CST">
  <testcase classname="com.test.automation.tests.script.SalesForceLoginAutomationScript" name="Forgot_Password4B" time="2.505"/>
  <testcase classname="com.test.automation.tests.script.SalesForceLoginAutomationScript" name="login_To_SalesForce2" time="0.0">
    <ignored/>
  </testcase> <!-- login_To_SalesForce2 -->
  <testcase classname="com.test.automation.tests.script.SalesForceLoginAutomationScript" name="Forgot_Password4A" time="0.0">
    <ignored/>
  </testcase> <!-- Forgot_Password4A -->
  <testcase classname="com.test.automation.tests.script.SalesForceLoginAutomationScript" name="Check_RemeberMe3" time="0.0">
    <ignored/>
  </testcase> <!-- Check_RemeberMe3 -->
  <testcase classname="com.test.automation.tests.script.SalesForceLoginAutomationScript" name="login_Error_Message1" time="0.0">
    <ignored/>
  </testcase> <!-- login_Error_Message1 -->
</testsuite> <!-- Default test -->
